ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: ${PORT:8080}
  database:
    driver: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ktor_sample}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
